import { Navbar } from "~/components/navber";
import "../styles/globals.css";
import Providers from "./providers";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body>
        <Providers>
          <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
            <div className="flex-grow">
              {children}
            </div>
            <Navbar />
          </main>
        </Providers>
      </body>
    </html>
  )
}
